services:
  authmaster:
    build:
      context: .
      dockerfile: authmaster-dockerfile
    depends_on:
      - postgres
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8520:3000"
  postgres:
    build:
      context: .
      dockerfile: postgres-dockerfile
    hostname: postgres
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  envoy_service:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: Dockerfile-envoy
    ports:
      - "8530:8000"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
volumes:
  postgres_data:
