# Build
FROM alpine:3.15.1 AS build

WORKDIR /app

RUN apk add --no-cache protoc

COPY ./authmaster/authmaster.proto .

RUN  protoc --include_imports --include_source_info --descriptor_set_out=authmaster.pb authmaster.proto

## Deploy stage
FROM envoyproxy/envoy:v1.22.0

COPY --from=build /app/authmaster.pb /tmp/
