/**
 * @fileoverview gRPC-Web generated client stub for authmaster
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.6
// source: authmaster.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as authmaster_pb from './authmaster_pb'; // proto import: "authmaster.proto"


export class AuthmasterClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorTestAuth = new grpcWeb.MethodDescriptor(
    '/authmaster.Authmaster/TestAuth',
    grpcWeb.MethodType.UNARY,
    authmaster_pb.TestAuthRequest,
    authmaster_pb.TestAuthResponse,
    (request: authmaster_pb.TestAuthRequest) => {
      return request.serializeBinary();
    },
    authmaster_pb.TestAuthResponse.deserializeBinary
  );

  testAuth(
    request: authmaster_pb.TestAuthRequest,
    metadata?: grpcWeb.Metadata | null): Promise<authmaster_pb.TestAuthResponse>;

  testAuth(
    request: authmaster_pb.TestAuthRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: authmaster_pb.TestAuthResponse) => void): grpcWeb.ClientReadableStream<authmaster_pb.TestAuthResponse>;

  testAuth(
    request: authmaster_pb.TestAuthRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: authmaster_pb.TestAuthResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/authmaster.Authmaster/TestAuth',
        request,
        metadata || {},
        this.methodDescriptorTestAuth,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/authmaster.Authmaster/TestAuth',
    request,
    metadata || {},
    this.methodDescriptorTestAuth);
  }

  methodDescriptorLogin = new grpcWeb.MethodDescriptor(
    '/authmaster.Authmaster/Login',
    grpcWeb.MethodType.UNARY,
    authmaster_pb.LoginRequest,
    authmaster_pb.LoginResponse,
    (request: authmaster_pb.LoginRequest) => {
      return request.serializeBinary();
    },
    authmaster_pb.LoginResponse.deserializeBinary
  );

  login(
    request: authmaster_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null): Promise<authmaster_pb.LoginResponse>;

  login(
    request: authmaster_pb.LoginRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: authmaster_pb.LoginResponse) => void): grpcWeb.ClientReadableStream<authmaster_pb.LoginResponse>;

  login(
    request: authmaster_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: authmaster_pb.LoginResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/authmaster.Authmaster/Login',
        request,
        metadata || {},
        this.methodDescriptorLogin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/authmaster.Authmaster/Login',
    request,
    metadata || {},
    this.methodDescriptorLogin);
  }

  methodDescriptorCreateUser = new grpcWeb.MethodDescriptor(
    '/authmaster.Authmaster/CreateUser',
    grpcWeb.MethodType.UNARY,
    authmaster_pb.CreateUserRequest,
    authmaster_pb.CreateUserResponse,
    (request: authmaster_pb.CreateUserRequest) => {
      return request.serializeBinary();
    },
    authmaster_pb.CreateUserResponse.deserializeBinary
  );

  createUser(
    request: authmaster_pb.CreateUserRequest,
    metadata?: grpcWeb.Metadata | null): Promise<authmaster_pb.CreateUserResponse>;

  createUser(
    request: authmaster_pb.CreateUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: authmaster_pb.CreateUserResponse) => void): grpcWeb.ClientReadableStream<authmaster_pb.CreateUserResponse>;

  createUser(
    request: authmaster_pb.CreateUserRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: authmaster_pb.CreateUserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/authmaster.Authmaster/CreateUser',
        request,
        metadata || {},
        this.methodDescriptorCreateUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/authmaster.Authmaster/CreateUser',
    request,
    metadata || {},
    this.methodDescriptorCreateUser);
  }

}

